HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {

    }

    public int StylistId { get; set; }
    public string Name { get; set; }

  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }


  }
}

HairSalon/Views/Home/Index.cshtml
<h1>Welcome to Salon Manager!</h1>

<p>@Html.ActionLink("See all stylists", "Index", "Stylists")</p>

HairSalon/Views/Stylists/Index.cshtml
@using HairSalon.Models;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No stylists have been added yet!</h3>
} 

<ul>
  @foreach(Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
  }
</ul>


<p>@Html.ActionLink("Home", "Index", "Home")</p>